# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:

  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      - uses: pcrockett/setup-yamlfmt@2949e59bb1f6d24f519d0dfa2560a0dbcd563fcc  # v0.1.1
      - uses: pcrockett/setup-shfmt@bf26c86e340dc10783e5c105cf09a459a6b45751  # v0.1.2
      - uses: pcrockett/setup-just@096177f0c832d972bdf47b0fac0e8b9c0eb49326  # v0.1.2
      - uses: pcrockett/setup-pre-commit@e7e4a210561b1c4114b3a45eddbdc67e39e81f21  # v0.1.2

      - run: just lint
